name: Schemathesis Test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Start containers
        run: docker compose up -d --build

      - uses: schemathesis/action@v1
        with:
          schema: "http://127.0.0.1:5123/openapi.json"

      - name: Stop containers
        if: always()
        run: docker-compose down
